# Generated by Django 5.2 on 2025-06-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='Название бренда')),
                ('brand_tonnage', models.IntegerField(blank=True, null=True, verbose_name='Грузоподъемность, кг')),
                ('brand_places', models.IntegerField(blank=True, null=True, verbose_name='Количество сидячих мест')),
                ('brand_tank', models.IntegerField(blank=True, null=True, verbose_name='Объем бака, л')),
                ('brand_door', models.IntegerField(blank=True, default=3, null=True, verbose_name='Количество дверей')),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
                'ordering': ['brand_id'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=20, verbose_name='Название предприятия')),
                ('e_city', models.CharField(max_length=20, verbose_name='Город нахождения')),
                ('e_address', models.CharField(blank=True, max_length=50, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['e_id'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(default='', max_length=30, verbose_name='ФИО водителя')),
                ('d_salary', models.IntegerField(verbose_name='Зарплата')),
                ('d_license', models.CharField(blank=True, max_length=20, verbose_name='Номер водительского удостоверения')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarPark.enterprise', verbose_name='Предприятие')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['d_id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(default='', max_length=10, verbose_name='Номер автомобиля')),
                ('car_cost', models.IntegerField(verbose_name='Цена')),
                ('car_year', models.IntegerField(verbose_name='Год выпуска')),
                ('car_mileage', models.IntegerField(verbose_name='Пробег')),
                ('car_color', models.CharField(verbose_name='Цвет')),
                ('active_driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicle', to='CarPark.driver', verbose_name='Активный водитель')),
                ('brand', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='CarPark.brand', verbose_name='ID Брэнда')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarPark.enterprise', verbose_name='Предприятие')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['car_id'],
            },
        ),
        migrations.CreateModel(
            name='DriverVehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активное назначение')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPark.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPark.vehicle')),
            ],
            options={
                'verbose_name': 'Назначение водителя',
                'verbose_name_plural': 'Назначения водителей',
                'unique_together': {('driver', 'vehicle')},
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicles',
            field=models.ManyToManyField(related_name='drivers', through='CarPark.DriverVehicleAssignment', to='CarPark.vehicle', verbose_name='Автомобили'),
        ),
    ]
