# Generated by Django 5.2 on 2025-06-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPark', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='enterprises', to='manager.manager'),
        ),
    ]
